# Generated by Django 5.2.7 on 2025-10-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_sales_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sales',
            new_name='is_sale',
        ),
    ]
