# Generated by Django 5.2.7 on 2025-11-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='proce',
            new_name='price',
        ),
    ]
